baseURL: https://olzhasar.com/
languageCode: en-us
title: Olzhas Arystanov

theme: PaperMod
params:
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: true

menu:
  main:
    - name: Posts
      url: /
      weight: 1
    - name: Projects
      url: projects/
      weight: 2
    - name: About
      url: about/
      weight: 3
